import Layout from "../../components/shared/Layout/Layout";
import { useSelector } from "react-redux";

export default function AdminHome() {
  const { user } = useSelector((state) => state.auth);
  return (
    <Layout>
      <div>
        <h1 className="text-4xl font-semibold tracking-tighter">
          Welcome, Admin <i className="gradient-text capitalize">{user?.name}</i>
        </h1>
        <h3>Manage blood bank app</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis ipsa amet, exercitationem iste minus necessitatibus aperiam totam eligendi nihil recusandae quia, mollitia atque illo repellat minima error, earum ducimus similique incidunt vero animi velit quam sed! Quia esse, nihil quidem incidunt provident quaerat fuga totam, eaque minus tenetur ducimus ea praesentium. Ut distinctio deserunt earum a quod architecto, nostrum, sapiente sed tempore voluptatum cumque id nobis eum atque? Voluptatum minima molestiae voluptatem autem optio sed, laboriosam repellat nostrum nesciunt nam alias magnam exercitationem obcaecati? Tempore, id aliquam veniam nihil at, provident, quasi iure repellendus quas totam nam consectetur ad pariatur ea dicta voluptatum dignissimos? Libero eaque nam maiores! Fuga ipsa, quam facere doloremque aliquid consequatur necessitatibus eum eius nemo officiis numquam! Incidunt fugit illo iure voluptatum non quasi porro nesciunt laboriosam repudiandae vel facere placeat numquam quod provident, accusamus eaque, dolor error recusandae. Voluptatum odit consectetur repellendus officiis eos, quae laboriosam sunt sed aspernatur nisi. Beatae, natus cum sit necessitatibus voluptates voluptas nulla ullam omnis et dolores explicabo nostrum? Ea, laboriosam debitis? Dolore possimus quis non et corporis fuga deserunt illum quae sed. Earum quam cupiditate saepe minus eius, repellendus beatae commodi nostrum pariatur veritatis maiores hic voluptates atque deleniti laboriosam quos in at quasi tenetur iusto unde omnis voluptatum possimus suscipit? Voluptates rerum exercitationem, blanditiis magni earum laboriosam consequuntur dolore facilis autem illo numquam cum ex similique reprehenderit recusandae dolorem voluptas sint eos ad incidunt nobis voluptatibus. Repellat esse numquam architecto eos voluptas ratione, quis excepturi tenetur non, dolor animi assumenda? Voluptates sunt nobis laboriosam est eveniet eaque aliquam explicabo, porro ab alias consequatur magni saepe praesentium? Earum laboriosam a repellendus vitae dolor vel aut molestias harum aliquid quia sapiente optio illo atque et ullam inventore fugit expedita blanditiis quidem, illum explicabo nesciunt ut sed soluta? Sint, odio nostrum omnis eum hic nobis suscipit quis rerum expedita quo cupiditate eveniet! Sed a ducimus voluptatibus optio perspiciatis deserunt inventore laboriosam molestias magni qui! Natus perspiciatis consequatur ad, omnis atque neque ratione ipsa accusantium nisi id soluta? Maiores ipsa molestiae sunt architecto? Illo assumenda quam voluptate praesentium rem iste mollitia nesciunt magni voluptatibus, cupiditate recusandae commodi sequi nostrum ipsam repellat iure sit molestiae repudiandae perspiciatis dolores hic. Dicta id, modi qui odit quasi dolorem eveniet minus minima ipsum, magnam ut quidem, voluptatum facilis dolore eligendi? Cupiditate, ad provident obcaecati dolore pariatur quam rem facilis voluptas delectus sit nam laudantium, vel atque!</p>
      </div>
    </Layout>
  );
}
